---
language: python
services: docker

matrix:
  include:
    - os: linux
      dist: xenial

before_script:
  - cd ../
  - mv ansible-role-disable-ipv6 disable-ipv6
  - cd disable-ipv6

install:
  - pip install molecule docker

script:
  - molecule lint
